# import = ["~/.config/alacritty/themes/kanagawa-dragon.toml"]
import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[font]
size = 14

[font.normal]
 family = "Hack Nerd Font"
#  family = "JetBrainsMono Nerd Font"
# family = "MesloLGS Nerd Font"

[font.offset]
# This is some random text to test font offsets
# This is also some random text to test font offsets
# This is also some random text to test font offsets
 y = 4

[window.dimensions]
columns = 290
lines = 90

[window.padding]
x = 5
