import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[font]
size = 14

[font.normal]
family = "Iosevka Nerd Font"

[font.offset]
y = 8

[window]
startup_mode = "Maximized"
decorations = "Buttonless"

[window.dimensions]
columns = 290
lines = 90

[window.padding]
x = 5
y = 10

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Command", chars = "\u0005" },
  { key = "Left", mods = "Command", chars = "\u0001" },
  { key =  "Back", mods =  "Command", chars =  "\u0015"}, 
  { key =  "Back", mods = "Alt", chars  = "\u001b\u007f"} 
]
